import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative w-full min-h-screen overflow-hidden">
          {/* Blurs fixos em vermelho dark */}
          <div className="fixed top-55 left-75 w-60 h-60 bg-red-700/40 rounded-full blur-3xl "></div>
          <div className="fixed top-40 left-120 w-95 h-80 opactiy-55 bg-red-600/30 rounded-full blur-3xl "></div>
          <div className="fixed top-0 -left-30 w-92 h-120 bg-red-600/20 rounded-full blur-3xl "></div>
          <div className="fixed top-20 left-120 w-70 h-100 opacity-20 bg-red-600/20 rounded-full blur-3xl "></div>

          {/* Conteúdo das páginas */}
          <main className="relative z-10">{children}</main>
        </div>
      </body>
    </html>
  );
}
